---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nodeport-gowebapp-service
#spec:
#  type: NodePort
#  selector:
#    app: gowebapp
#
#  ports:
#    - nodePort: 31337
#      port: 8080
#      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: gowebapp-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: gowebapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobweapp-vps
spec:
  selector:
    matchLabels:
      app: gowebapp-vps
  replicas: 1
  template:
    metadata:
      labels:
        app: gowebapp-vps
    spec:
      containers:
      - name: gowebapp-vps
        image: ubuntu:latest
        command: [ "sleep", "infinity" ]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobweapp-deployment
spec:
  selector:
    matchLabels:
      app: gowebapp
  replicas: 10
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
      - name: gowebapp
        image: truebad0ur/gowebapp:v5
        #image: alpine:latest
        #command: [ "sleep", "infinity" ]
        ports:
        - containerPort: 8080
