---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-gowebapp-service
spec:
  type: NodePort
  selector:
    app: gowebapp

  ports:
    - nodePort: 31337
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobweapp-deployment
spec:
  selector:
    matchLabels:
      app: gowebapp
  replicas: 10
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
      - name: gowebapp
        image: truebad0ur/gowebapp:v5
        ports:
        - containerPort: 8080
